Makefile
README.md
resources/fluree_start.sh

This will help us update the Homebrew formula in our tap repo.

Add make install target for system-wide installation

---

src/fluree/db/server.clj

I ran into a test failure on master where the full-text indexer was trying to write to `/fluree` and getting a permission error as a result. It looks like this is because the tests use the memory storage option and so the file-storage-path wasn't set. The full-text indexer requires file storage (for now; changing that is a bigger lift), so this code makes it not startup if you're not using the file storage option and doesn't associate it into the conn unless it isn't nil.
Would love to get @zonotope's eyes on this especially.

Fix: full-text indexer requires file storage

---

src/fluree/db/peer/websocket.clj

Updates were not pushed to JS clients when a "root" auth was specified.  Flakes were filtered because of how the auth was attached to the "db".

FC-948 fix where all flakes filtered for root auth

---

test/fluree/db/ledger/api/downloaded.clj
test/fluree/db/ledger/docs/query/basic_query.clj
test/fluree/db/ledger/general/todo_permissions.clj
test/fluree/db/ledger/ledger_test.clj
test/fluree/db/ledger/test_helpers.clj

Added unit tests for view, update, delete of own to-dos based on the relationship? to submitting auth. 
Re-added unit tests where exception info was passed across an async channel.

FC-1010, FC-1004 Update/unit tests

---

src/fluree/db/peer/messages.clj

Syncing the websocket delete-ledger request with the http-api version, which actually deletes files, etc so that the ledger name can be re-used.
Also, cleaned up some code related to acquiring the connection object.

FC-1093 sync ws delete-ledger w/http-api version

---

Makefile
src/fluree/db/ledger/consensus/raft.clj

I noticed this bug while working on a bigger dynamic cluster sizing improvement. Compare to line 887 for reference.

Fix bug in join? == true branch of launch-raft-server

---

test/fluree/db/ledger/docs/query/sql_query.clj
test/fluree/db/ledger/ledger_test.clj

Add a few unit tests for SQL equality, inequality checks

FC-1087 add unit tests for SQL <=, >=

---

src/fluree/db/server_settings.clj

The storage-type wasn't making it into the group settings (just conn), so the only-leader-snapshots logic was always true. Fixes FC-1118.
The expected behavior is that all nodes should generate raft snapshots when the `storage-type` is `:file`.

FC-1118: Fix bug where only leader snapshots even w/ file storage

---

src/fluree/db/ledger/consensus/raft.clj
src/fluree/db/server_settings.clj

Appears to fix FC-1130, but is definitely a fix either way.

FC-1130 - Fix snapshot install path

---

src/fluree/db/ledger/transact/schema.clj

Assertion errors are not caught by 'Exception' class, change assertions to standard errors

FC-1128 Assertion errors in tx validation fns not catching

---

src/fluree/db/ledger/txgroup/monitor.clj

Modified the select-block-commands process to use the txMax db setting when provided.  Otherwise, the default of 2mb is used for maximum transaction size.  [The default value is now defined as a constant, making it available for unit tests.]

FC-1162 use txMax db setting when provided

---

deps.edn
src/fluree/db/ledger/storage/s3store.clj

This merge includes the following items:
- FC-1161 Throw an exception when the _list bucket contents_ request to AWS fails
- FC-1168 Update the AWS S3 dependencies to the latest version
Note that all unit tests are passing locally.

FC-1161, FC-1168 Update/aws s3 version

---

src/fluree/db/ledger/transact/validation.clj

no longer do tx validation fns building in background

FC-1178: Fix for test hanging / resource contention

---

deps.edn

Updated dependencies related to build

FC-1185 update dependencies

---

src/fluree/db/ledger/transact/error.clj
test/fluree/db/ledger/docs/transact/transactions.clj

The correct error is not being propagated because an async/go was missing.  
Also added a test for an expired transaction.

Wrap transaction error handler in go-try

---

src/fluree/db/ledger/transact.clj
src/fluree/db/ledger/transact/error.clj
src/fluree/db/ledger/transact/json.clj

Small cleanups related to transactions from prior PR

FC-1222 Transaction cleanups

---

resources/fluree_sample.properties
src/fluree/db/server_settings.clj

...and add fdb-group-port to master list of config params w/ an
explanation of what it does when.

Remove unused ledger-port config param

---

dev/user.clj
test/fluree/db/ledger/Resources/ChatApp/chatPreds.edn

The code here consists of a few functions I found useful while debugging the wildcard query issues reported in FC-1275. The fix turned out to be fully contained in the db library and there are no user-facing changes here, but I think these dev-mode functions would be useful for me and future developers in fluree core going forward. Hence this pr.

FC-1275 (i guess): Dev utility functions

---

test/fluree/db/ledger/Resources/invoice/data.edn
test/fluree/db/ledger/Resources/invoice/schema.edn
test/fluree/db/ledger/api/downloaded.clj
test/fluree/db/ledger/general/invoice_tests.clj
test/fluree/db/ledger_test.clj
test/fluree/db/peer/http_api_tests.clj
test/fluree/db/test_helpers.clj

Added unit tests for password authentication, which included setting up a invoice ledger

unit tests for password authentication (FC-1315)

---

deps.edn
src/fluree/db/peer/http_api.clj

...in http-api. Depends on the addition of util.async/alts?? to db library.
Part of the fix for FC-1338

FC-1338 - Use alts?? to throw exceptions in storage-handler

---

src/fluree/db/ledger/transact/core.clj
test/fluree/db/ledger/general/todo_permissions.clj

@bplatz There are a couple of places that we can check whether or not a `ref` object is in the designated`restrictCollection`.  I added the `restrictCollection` check to the point where we validate that the `ref` id exists.  We could push the check later in the process, perhaps when we validate predicate/collection specs.
---
At some point, we lost the validation that a 'ref' id is actually contained in the `restrictCollection`.  This change applies the check when the `ref` is verified to exist.
Added a unit test as well.

Enforce restrictCollection property [FC-1345]

---

src/fluree/db/peer/http_api.clj
src/fluree/db/peer/messages.clj
src/fluree/db/server_settings.clj
test/fluree/db/ledger/api/closed_test.clj
test/fluree/db/ledger/api/open_test.clj
test/fluree/db/test_helpers.clj

Once I got the tests working correctly they passed, so it seems like /history and /block work OK w/ http-sig requests

Tests: signing history & block queries

---

Makefile
src/fluree/db/peer/http_api.clj

Just a couple Makefile fixes I did while working on https://github.com/fluree/db/pull/162 (plus a couple small log level changes)

Makefile improvements

---

src/fluree/db/ledger/garbage_collect.clj
src/fluree/db/peer/http_api.clj

Tested locally and seemed to do the right things with and without garbage

Expose /garbage-collect endpoint in HTTP API

---

deps.edn
test-resources/data/bike-categories.edn
test-resources/schemas/category.edn
test/fluree/db/ledger/api/open_test.clj

...and use compatible commit of db library or else they fail.

Add tests for recursive queries

---

deps.edn
test/fluree/db/ledger/docs/query/advanced_query.clj

Add tests for groupBy offset and limit quey

FC-1410 Add groupBy limit and offset test, update db dep

---

deps.edn
test/fluree/db/ledger/docs/query/advanced_query.clj
test/fluree/db/ledger/docs/query/sparql.clj

Corresponding ledger updates for fluree/db updates that support this new capability.
This adds several tests.

FC-1411 Feature - 'having' in 'groupBy' queries

---

deps.edn
test/fluree/db/ledger/docs/query/basic_query.clj

This adds test for FC-1418 and FC-1417

FC-1418 - add tests

---

deps.edn

Bump fluree/db dep for latest

---

dev-resources/data/chat.edn
test/fluree/db/ledger/docs/getting_started/basic_schema.clj
test/fluree/db/ledger/docs/identity/signatures_test.clj
test/fluree/db/ledger/docs/query/advanced_query.clj
test/fluree/db/ledger/docs/query/sql_query.clj
test/fluree/db/ledger/query/analytical_test.clj
test/fluree/db/ledger/query/basic_test.clj

This adds tests for query types we recently fixed in a couple of db PRs (https://github.com/fluree/db/pull/186 & https://github.com/fluree/db/pull/188).

Add tests for some query types

---

src/fluree/db/ledger/consensus/raft.clj

In debugging FC-1428 I noticed that the old raft snapshot data looked like `{:networks {"nw-name" {:dbs {"ledger-id" ...}}}}` and the system couldn't see them as a result b/c it's looking for `:ledgers` now. This adds an upgrade fn that (for now) just replaces those `:dbs` keys with `:ledgers` but leaves room for additional upgrades we may want / need to do to these snapshots down the road. It only does this once on startup and subsequent snapshots should have the new format.
The actual fix is 1ddb5930ab7cec41cf0d5d5c2998948f76fa42de, the other commit is just code reformatting.

Update old snapshot format w/ :dbs to :ledgers when we read them in from disk

---

deps.edn
test/fluree/db/ledger/indexing_test.clj

This is the ledger side of https://github.com/fluree/db/pull/195, and it's just test additions/updates and it pulls in the new db dep.

FC-1431: fix/unresolve nodes

---

Dockerfile
deps.edn
test/fluree/db/ledger/query/analytical_test.clj

Adds tests for queries that weren't working before https://github.com/fluree/db/pull/196

Add orderBy variable query tests

---

deps.edn
src/fluree/db/peer/messages.clj
test/fluree/db/ledger/api/downloaded.clj

Along with https://github.com/fluree/db/pull/198 this fixes the `api/delete-ledger(-async)` fns and adds a test for them.

Fix delete-ledger api fns

---

deps.edn
test/fluree/db/ledger/query/analytical_test.clj

Tests for filter vars in queries. One of them tests for the fix in https://github.com/fluree/db/pull/201.

Add a couple tests for filter vars

---

deps.edn
test/fluree/db/ledger/predicate/json_test.clj

Adds a test for the type of query fixed by https://github.com/fluree/db/pull/206.

Add a test for deserializing JSON in query w/ orderBy
